name: build-source

on: [push]

jobs:
  build-source:
    runs-on: ubuntu-latest
    container:
      image: node:12-alpine
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Build source
        run: yarn build
