name: deploy-cloudflare-workers

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy-cloudflare-workers:
    runs-on: ubuntu-latest
    container: boringcodes/dev-runner:node-15-alpine
    name: With Node.js 15
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Build source
        run: yarn build
      - name: Deploy to CloudFlare Workers
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{secrets.CF_API_TOKEN}}
