name: push-dockerhub

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  push-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          # Replace organization/repository with your DockerHub organization & repository
          images: organization/repository
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          # Create your own token at https://github.com/organization/repository/settings/secrets
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Build & Push image to DockerHub
        id: build_push_image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{steps.docker_meta.outputs.tags}}
          labels: ${{steps.docker_meta.outputs.labels}}
      - name: Image digest
        run: echo ${{steps.build_push_image.outputs.digest}}
